# Generated by Django 4.2.1 on 2023-08-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
