# Generated by Django 4.2.1 on 2023-08-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0003_movie_image_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
