# Generated by Django 4.2.1 on 2023-08-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0005_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
