# Generated by Django 4.2.1 on 2023-08-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0007_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='downloadlADlink',
            new_name='downloadlDIRECTlink',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
    ]
