# Generated by Django 4.2.1 on 2023-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0008_rename_downloadladlink_movie_downloadldirectlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movielinkonwebsite',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
