# Generated by Django 4.2.1 on 2023-08-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0009_movie_movielinkonwebsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
