# Generated by Django 4.2.1 on 2023-08-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0011_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movielinkonwebsite',
        ),
    ]
