# Generated by Django 4.2.1 on 2023-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0013_movie_movielinkonwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trendingORHighImdbratedORNone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
