# Generated by Django 4.2.1 on 2023-08-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0015_rename_trendingorhighimdbratedornone_movie_trendingorhighimdbratedorlatestornone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_file',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
