# Generated by Django 4.2.1 on 2023-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0017_movie_completedyesorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='CompletedYESorNO',
            field=models.CharField(default='Yes', max_length=500, null=True),
        ),
    ]
